/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador_Principal;
import Modelo.Almacenamiento;
import Modelo.BCP;
import Modelo.Memoria;

import java.io.File;
import java.time.LocalTime;
import java.util.List;
import java.util.Map;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edurg
 */
public class Ventana_Principal extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(Ventana_Principal.class.getName());

        private static Controlador_Principal controlador_principal;

        private Boolean bloqueo = false;

        /**
         * Creates new form Ventana_Principal
         */
        public Ventana_Principal() {
                initComponents();
                controlador_principal = new Controlador_Principal();

                // Incializar el contenido base de las tablas.
                iniciar_Contenido_Base_tablas();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ejecutar_BTN = new javax.swing.JButton();
        Paso_A_Paso_BTN = new javax.swing.JButton();
        Limpiar_BTN = new javax.swing.JButton();
        Estadisticas_BTN = new javax.swing.JButton();
        Cargar_Archivos_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Procesos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_BCP = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Memoria = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla_Almacenamiento = new javax.swing.JTable();
        Lista_Procesos_Label = new javax.swing.JLabel();
        BCP_Label = new javax.swing.JLabel();
        Memoria_Label = new javax.swing.JLabel();
        Almacenamiento_Label = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        terminal_Text_Area = new javax.swing.JTextArea();
        Terminal_Text_Area_Label = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tabla_Estadisticas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        Ejecutar_BTN.setText("Ejecutar");
        Ejecutar_BTN.addActionListener(this::Ejecutar_BTNActionPerformed);

        Paso_A_Paso_BTN.setText("Paso a paso");
        Paso_A_Paso_BTN.addActionListener(this::Paso_A_Paso_BTNActionPerformed);

        Limpiar_BTN.setText("Limpiar");
        Limpiar_BTN.addActionListener(this::Limpiar_BTNActionPerformed);

        Estadisticas_BTN.setText("Estadisticas");
        Estadisticas_BTN.addActionListener(this::Estadisticas_BTNActionPerformed);

        Cargar_Archivos_BTN.setText("Cargar Archivos");
        Cargar_Archivos_BTN.addActionListener(this::Cargar_Archivos_BTNActionPerformed);

        Tabla_Procesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Procesos);

        Tabla_BCP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PID:", null},
                {"Estado:", null},
                {"Prioridad:", null},
                {"Inicio Memoria:", null},
                {"Final Memoria:", null},
                {"PC:", null},
                {"IR:", null},
                {"AC:", null},
                {"AX:", null},
                {"BX", null},
                {"CX:", null},
                {"DX:", null},
                {"AH:", null},
                {"AL:", null},
                {"Lista Archivos:", null},
                {"CPU Asignada:", null},
                {"Tiempo Llegada:", null},
                {"Tiempo Inicio:", null},
                {"Tiempo Finalización:", null},
                {"Duración Estimada:", null},
                {"Proximo Proceso:", null},
                {"Pila (0):", null},
                {"Pila (1):", null},
                {"Pila (2):", null},
                {"Pila (3):", null},
                {"Pila (4):", null}
            },
            new String [] {
                "Dato", "Valor"
            }
        ));
        jScrollPane2.setViewportView(Tabla_BCP);

        Tabla_Memoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tabla_Memoria);

        Tabla_Almacenamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Valor"
            }
        ));
        jScrollPane4.setViewportView(Tabla_Almacenamiento);

        Lista_Procesos_Label.setText("Lista de procesos");

        BCP_Label.setText("BCP");

        Memoria_Label.setText("Memoria");

        Almacenamiento_Label.setText("Almacenamiento");

        terminal_Text_Area.setColumns(20);
        terminal_Text_Area.setRows(5);
        jScrollPane5.setViewportView(terminal_Text_Area);

        Terminal_Text_Area_Label.setText("Terminal");

        Tabla_Estadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Inicio", "Finalización", "Diferencia"
            }
        ));
        jScrollPane6.setViewportView(Tabla_Estadisticas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Sistema Operativo V1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Cargar_Archivos_BTN)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(Lista_Procesos_Label)
                                .addGap(177, 177, 177)
                                .addComponent(BCP_Label)
                                .addGap(199, 199, 199)
                                .addComponent(Memoria_Label)
                                .addGap(170, 170, 170)
                                .addComponent(Almacenamiento_Label)
                                .addGap(187, 187, 187)
                                .addComponent(Terminal_Text_Area_Label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ejecutar_BTN)
                                .addGap(32, 32, 32)
                                .addComponent(Paso_A_Paso_BTN)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Limpiar_BTN)
                                        .addGap(18, 18, 18)
                                        .addComponent(Estadisticas_BTN))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejecutar_BTN)
                    .addComponent(Paso_A_Paso_BTN)
                    .addComponent(Limpiar_BTN)
                    .addComponent(Estadisticas_BTN))
                .addGap(28, 28, 28)
                .addComponent(Cargar_Archivos_BTN)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lista_Procesos_Label)
                    .addComponent(BCP_Label)
                    .addComponent(Memoria_Label)
                    .addComponent(Almacenamiento_Label)
                    .addComponent(Terminal_Text_Area_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void Ejecutar_BTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Ejecutar_BTNActionPerformed

                if (this.bloqueo)
                        return;

                SwingWorker<Void, Void> worker = new SwingWorker<>() {
                        @Override
                        protected Void doInBackground() throws Exception {
                                while (controlador_principal.hay_Procesos_Nuevos()) {
                                        while (!controlador_principal.comprobar_Finalizacion_Proceso()) {
                                                if (bloqueo)
                                                        return null;

                                                List<String> estado_Ejecucion = controlador_principal.paso_a_paso();
                                                if (estado_Ejecucion == null) {
                                                        SwingUtilities.invokeLater(() -> {
                                                                limpiar_tabla_BCP();
                                                                limpiar_terminal();
                                                        });
                                                        return null;
                                                }

                                                String lineaActual = estado_Ejecucion.get(0);
                                                switch (lineaActual) {
                                                        case "1":
                                                                JOptionPane.showMessageDialog(null,
                                                                                "Error: " + estado_Ejecucion.get(1));
                                                                break;
                                                        case "2":
                                                                bloqueo = true;
                                                                entrada_Por_Teclado();
                                                                break;
                                                        case "3":
                                                                imprimiar_En_Pantalla(estado_Ejecucion.get(1));
                                                                break;
                                                        case "4":
                                                                limpiar_tabla_BCP();
                                                                limpiar_terminal();
                                                                break;
                                                }

                                                controlador_principal.activar_Espera();

                                                // Actualizar tablas en el EDT
                                                SwingUtilities.invokeLater(() -> actualizar_Tablas());
                                        }
                                        controlador_principal.procesar_Finalizacion_Proceso();
                                }
                                return null;
                        }
                };
                worker.execute();

        }

        private void Paso_A_Paso_BTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Paso_A_Paso_BTNActionPerformed

                // No permitir realizar acciones en lo que se espera a que
                // termine la interrupcion.
                if (this.bloqueo == true) {
                        return;
                }

                List<String> estado_Ejecucion = this.controlador_principal.paso_a_paso();

                if (estado_Ejecucion == null) {
                        this.limpiar_tabla_BCP();
                        this.limpiar_terminal();
                        return;
                }
                // Procesar la que viene en la salida del estado.

                String lineaActual = estado_Ejecucion.get(0);

                if (lineaActual.equals("1")) {
                        // Error.
                        // Mostrar el mensaje del error
                        JOptionPane.showMessageDialog(null, "Error: " + estado_Ejecucion.get(1));

                } else if (lineaActual.equals("2")) {
                        // Leer teclado.
                        this.bloqueo = true;
                        this.entrada_Por_Teclado();

                } else if (lineaActual.equals("3")) {
                        // Imprimir en pantalla.
                        this.imprimiar_En_Pantalla(estado_Ejecucion.get(1));

                } else if (lineaActual.equals("4")) {
                        // Terminar el proces.
                        // en este basicamente no se hace nada, ya que el procesamiento se hace en la
                        // instruccion.
                        limpiar_tabla_BCP();
                        limpiar_terminal();

                }

                this.actualizar_Tablas();

        }

        private void Limpiar_BTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Limpiar_BTNActionPerformed

                this.controlador_principal.reiniciar_programa();
                this.iniciar_Contenido_Base_tablas();
                this.bloqueo = false;

                // Tambien es necesario uno para limpiar la parte de la terminal, de la BCP
                // y de la lista de proces.
        }

        private void Estadisticas_BTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Estadisticas_BTNActionPerformed

                // No permitir realizar acciones en lo que se espera a que
                // termine la interrupcion.
                if (this.bloqueo == true) {
                        return;
                }

                // 1. Obtener las estadisticas
                List<BCP> estadisticas = this.controlador_principal.getLista_Procesos_Terminados();

                // 2. Actualizar la tabla
                actualizar_Tabla_Estadisticas(estadisticas);

        }// GEN-LAST:event_Estadisticas_BTNActionPerformed

        private void Cargar_Archivos_BTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Cargar_Archivos_BTNActionPerformed

                // Validar si se ha agregado memoria. -> Pendiente de revisar si es necesari
                // esta validacion.
                // if (control_programa.getMemoria() == null) {
                // JOptionPane.showMessageDialog(null, "Por favor, crea una memoria antes de
                // cargar un archivo.");
                // return;
                // }

                // try {
                JFileChooser seleccion_Archivos = new JFileChooser(); // Crear el componente.

                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos ASM", "asm"); // filtro
                                                                                                     // para
                                                                                                     // solo
                                                                                                     // agregar
                // archivos .asm

                seleccion_Archivos.setFileFilter(filtro); // Agregar el filtro.

                seleccion_Archivos.setAcceptAllFileFilterUsed(false); // No permitir todos los archivos.

                // ---- Modificacion para permitir la carga de multiples archivos a la vez.

                seleccion_Archivos.setMultiSelectionEnabled(true); // Permitir la seleccion de varios archivos.

                int opcion = seleccion_Archivos.showOpenDialog(this);

                if (opcion == JFileChooser.APPROVE_OPTION) {
                        File[] archivosASM = seleccion_Archivos.getSelectedFiles();

                        for (File archivo : archivosASM) {
                                // System.out.println("-> Archivo: " + archivo.getName());
                                if (archivo != null) {
                                        String ruta_Archivo = archivo.getAbsolutePath();
                                        List<String> resultado = controlador_principal.cargar_archivo(ruta_Archivo,
                                                        archivo.getName());

                                        // Descripcion detallada de los errores.
                                        if (!resultado.get(0).equals("0")) {
                                                // Mostrar el error
                                                JOptionPane.showMessageDialog(null, resultado.get(1));
                                        }
                                }
                        }
                }

                // Actualizar el contenido de la tabla de almacenamiento.
                actualizar_tabla_Almacenamiento(controlador_principal.getAlmacenamiento());

                // Actualizar la tabla de memoria por si se va a agregar un nuevo proceso:
                actualizar_tabla_Memoria(controlador_principal.getMemoria());

                // Actualizar la tabla de procesos por si se va a agregar un nuevo proceso:
                actualizar_Tabla_Procesos();

                // Actualizar la tabla BCP por si se va a agregar un nuevo proceso:
                actualizar_Tabla_BCP();

                // } catch (Exception e) {
                // // Mostrar un mensaje de error:
                // JOptionPane.showMessageDialog(null,
                // "Error al cargar archivos: " + e.getMessage());
                // }

        }

        // ######### Seccion para el trabajo con las tablas. ##############

        public void actualizar_Tablas() {
                // Actualizar el contenido de la tabla de almacenamiento.
                actualizar_tabla_Almacenamiento(controlador_principal.getAlmacenamiento());

                // Actualizar la tabla de memoria por si se va a agregar un nuevo proceso:
                actualizar_tabla_Memoria(controlador_principal.getMemoria());

                // Actualizar la tabla de procesos por si se va a agregar un nuevo proceso:
                actualizar_Tabla_Procesos();

                // Actualizar la tabla BCP por si se va a agregar un nuevo proceso:
                actualizar_Tabla_BCP();
        }

        public void iniciar_Contenido_Base_tablas() {
                // DefaultTableModel modelo_Tabla_Indices = (DefaultTableModel)
                // Tabla_Indices.getModel();
                // DefaultTableModel modelo_Tabla_Programas = (DefaultTableModel)
                // Tabla_Programas.getModel();

                // modelo_Tabla_Indices.setRowCount(0);
                // modelo_Tabla_Programas.setRowCount(0);

                // Seccion para la tabla de procesos.
                DefaultTableModel modelo_Tabla_Procesos = (DefaultTableModel) Tabla_Procesos.getModel();

                modelo_Tabla_Procesos.setRowCount(0);

                for (int i = 0; i < 20; i++) {
                        modelo_Tabla_Procesos.addRow(new Object[] { " ", " " });
                }
                // Seccion para la tabla de memoria.
                actualizar_tabla_Memoria(controlador_principal.getMemoria());

                // Seccion para la tabla de almacenamiento.
                actualizar_tabla_Almacenamiento(controlador_principal.getAlmacenamiento());
        }

        public void actualizar_Tabla_Procesos() {
                // Primero se obtiene el modelo de la tabla.
                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla_Procesos.getModel();

                // Segundo se limpia la tabla.
                modeloTabla.setRowCount(0);

                Map<Integer, String> lista_Procesos = controlador_principal.getLista_Proceso();

                for (Map.Entry<Integer, String> entry : lista_Procesos.entrySet()) {
                        int pid = entry.getKey();
                        String estado = entry.getValue();
                        modeloTabla.addRow(new Object[] { pid, estado });
                }
        }

        public void actualizar_Tabla_BCP() {
                // Primero se obtiene el modelo de la tabla.
                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla_BCP.getModel();

                // Segundo se limpia la tabla.
                // modeloTabla.setRowCount(0);

                BCP datos_BCP = controlador_principal.obtener_Datos_BCP_Actual();

                if (datos_BCP == null) {
                        return;
                }

                modeloTabla.setValueAt(datos_BCP.getPID(), 0, 1); // PID
                modeloTabla.setValueAt(datos_BCP.getEstado(), 1, 1); // estado
                modeloTabla.setValueAt(datos_BCP.getPrioridad(), 2, 1); // prioridad
                modeloTabla.setValueAt(datos_BCP.getMem_Init(), 3, 1); // MEM_PTR
                modeloTabla.setValueAt(datos_BCP.getMem_End(), 4, 1); // LIMIT
                modeloTabla.setValueAt(datos_BCP.getPC(), 5, 1); // PC
                modeloTabla.setValueAt(datos_BCP.getIR(), 6, 1); // IR

                modeloTabla.setValueAt(datos_BCP.getAC(), 7, 1); // AC
                modeloTabla.setValueAt(datos_BCP.getAX(), 8, 1); // AX
                modeloTabla.setValueAt(datos_BCP.getBX(), 9, 1); // BX
                modeloTabla.setValueAt(datos_BCP.getCX(), 10, 1); // CX
                modeloTabla.setValueAt(datos_BCP.getDX(), 11, 1); // DX
                modeloTabla.setValueAt(datos_BCP.getAH(), 12, 1); // AH
                modeloTabla.setValueAt(datos_BCP.getAL(), 13, 1); // AL

                modeloTabla.setValueAt(datos_BCP.getIO_STATUS(), 14, 1); // Lista Archivos
                modeloTabla.setValueAt(datos_BCP.getCPU_Asignada(), 15, 1); // CPU_TIME
                modeloTabla.setValueAt(datos_BCP.getTiempo_Llegada(), 16, 1); // Tiempo_Llegada
                modeloTabla.setValueAt(datos_BCP.getTiempo_Inicio(), 17, 1); // Tiempo_Inicio
                modeloTabla.setValueAt(datos_BCP.getTiempo_Finalizacion(), 18, 1); // Tiempo_Finalizacion
                modeloTabla.setValueAt(datos_BCP.getTiempo_Ejecucion(), 19, 1); // Tiempo_Ejecucion
                modeloTabla.setValueAt(datos_BCP.getProximo_Proceso(), 20, 1); // Proximo_Proceso
                int[] pila = datos_BCP.getPila();
                for (int i = 0; i < pila.length; i++) {
                        modeloTabla.setValueAt(pila[i], i + 21, 1); // Pila
                }

                // {"PID:", null}, // 0
                // {"Estado:", null}, //1
                // {"Prioridad:", null}, //2
                // {"Inicio Memoria:", null}, //3
                // {"Final Memoria:", null}, //4
                // {"PC:", null}, //5
                // {"IR:", null}, //6
                // {"AC:", null}, //7
                // {"AX:", null}, //8
                // {"BX", null}, //9
                // {"CX:", null}, //10
                // {"DX:", null}, //11
                // {"AH:", null}, //12
                // {"AL:", null}, //13
                // {"Lista Archivos:", null}, //14
                // {"CPU Asignada:", null}, //15
                // {"Tiempo Llegada:", null}, //16
                // {"Tiempo Inicio:", null}, //17
                // {"Tiempo Finalización:", null}, //18
                // {"Duración Estimada:", null}, //19
                // {"Proximo Proceso:", null}, //20
                // {"Pila (0):", null}, //21
                // {"Pila (1):", null}, //22
                // {"Pila (2):", null}, //23
                // {"Pila (3):", null}, //24
                // {"Pila (4):", null} //25

        }

        public void actualizar_tabla_Memoria(Memoria pMemoria) {
                // Aqui lo que se hace es actulizar la tabla con los valores de la memoria.
                // Se tiene que recorrer la memoria y llenar la tabla con los valores.

                if (pMemoria == null) {
                        return;
                }

                // Primero se obtiene el modelo de la tabla.
                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla_Memoria.getModel();

                // Segundo se limpia la tabla.
                modeloTabla.setRowCount(0);

                Map<Integer, String> memoria_Actual = pMemoria.getMemoria_Principal();

                for (int i = 0; i < pMemoria.getEspacio_Total(); i++) {
                        // memoria_Tabla.setValueAt(i, i, 0);
                        modeloTabla.addRow(new Object[] { i, memoria_Actual.get(i) });
                }
        }

        public void actualizar_tabla_Almacenamiento(Almacenamiento pAlmacenamiento) {
                // Aqui lo que se hace es actulizar la tabla con los valores del almacenamiento.
                // Se tiene que recorrer el almacenamiento y llenar la tabla con los valores.

                if (pAlmacenamiento == null) {
                        return;
                }

                // Primero se obtiene el modelo de la tabla.
                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla_Almacenamiento.getModel();

                // Segundo se limpia la tabla.
                modeloTabla.setRowCount(0);

                Map<Integer, String> almacenamiento_Actual = pAlmacenamiento.getMemoria_Secundaria();

                for (int i = 0; i < pAlmacenamiento.getTamano_Total(); i++) {
                        // almacenamiento_Tabla.setValueAt(i, i, 0);
                        modeloTabla.addRow(new Object[] { i, almacenamiento_Actual.get(i) });
                }
        }

        public void limpiar_terminal() {
                // Este seria la parte del text_Area_Terminal.
                terminal_Text_Area.setText("");
        }

        public void limpiar_tabla_BCP() {

                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla_BCP.getModel();
                modeloTabla.setValueAt("", 0, 1); // PID
                modeloTabla.setValueAt("", 1, 1); // estado
                modeloTabla.setValueAt("", 2, 1); // prioridad
                modeloTabla.setValueAt("", 3, 1); // MEM_PTR
                modeloTabla.setValueAt("", 4, 1); // LIMIT
                modeloTabla.setValueAt("", 5, 1); // PC
                modeloTabla.setValueAt("", 6, 1); // IR

                modeloTabla.setValueAt("", 7, 1); // AC
                modeloTabla.setValueAt("", 8, 1); // AX
                modeloTabla.setValueAt("", 9, 1); // BX
                modeloTabla.setValueAt("", 10, 1); // CX
                modeloTabla.setValueAt("", 11, 1); // DX
                modeloTabla.setValueAt("", 12, 1); // AH
                modeloTabla.setValueAt("", 13, 1); // AL

                modeloTabla.setValueAt("", 14, 1); // Lista Archivos
                modeloTabla.setValueAt("", 15, 1); // CPU_TIME
                modeloTabla.setValueAt("", 16, 1); // Tiempo_Llegada
                modeloTabla.setValueAt("", 17, 1); // Tiempo_Inicio
                modeloTabla.setValueAt("", 18, 1); // Tiempo_Finalizacion
                modeloTabla.setValueAt("", 19, 1); // Tiempo_Ejecucion
                modeloTabla.setValueAt("", 20, 1); // Proximo_Proceso

                for (int i = 0; i < 5; i++) {
                        modeloTabla.setValueAt("", i + 21, 1); // Pila
                }

        }

        public void limpiar_Tabla_Procesos() {
                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla_Procesos.getModel();
                modeloTabla.setRowCount(0);
        }

        public void actualizar_Tabla_Estadisticas(List<BCP> pLista_BCP) {
                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla_Estadisticas.getModel();
                modeloTabla.setRowCount(0);

                for (BCP bcp : pLista_BCP) {

                        int pid = bcp.getPID();

                        // Obtener momentos
                        LocalTime inicio = bcp.get_momento_creacion();
                        LocalTime fin = bcp.get_momento_finalizacion();

                        // Calcular diferencia en segundos
                        long diferencia = 0;
                        if (inicio != null && fin != null) {
                                diferencia = java.time.Duration.between(inicio, fin).getSeconds();
                        }

                        // Crear fila
                        Object[] row = new Object[] {
                                        pid,
                                        inicio != null ? inicio.toString() : "-",
                                        fin != null ? fin.toString() : "-",
                                        diferencia
                        };

                        modeloTabla.addRow(row);
                }
        }

        public void imprimiar_En_Pantalla(String pMensaje) {

                String mensajeAnterior = terminal_Text_Area.getText();

                // Si hay un mensaje anterior y no está vacío, agregamos un salto de línea
                if (mensajeAnterior != null && !mensajeAnterior.isEmpty()) {
                        terminal_Text_Area.setText(mensajeAnterior + "\n" + "> Print:" + pMensaje);
                } else {
                        terminal_Text_Area.setText(pMensaje);
                }
        }

        public void entrada_Por_Teclado() {
                // Utiliza el text Area para poder leer la entrada del usuario.
                String mensajeAnterior = terminal_Text_Area.getText();

                // Si hay un mensaje anterior y no está vacío, agregamos un salto de línea
                if (mensajeAnterior != null && !mensajeAnterior.isEmpty()) {
                        terminal_Text_Area.setText(mensajeAnterior + "\n" + "> Input: ");
                } else {
                        terminal_Text_Area.setText("> Input: ");
                }
                setupInputListener();
        }

        public void setupInputListener() {
                terminal_Text_Area.addKeyListener(new java.awt.event.KeyAdapter() {
                        @Override
                        public void keyPressed(java.awt.event.KeyEvent evt) {

                                if (bloqueo == false) {
                                        return;
                                }

                                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                                        evt.consume(); // evitar que se agregue un salto de línea automático

                                        String texto = terminal_Text_Area.getText();
                                        int idx = texto.lastIndexOf("> Input:");
                                        if (idx != -1) {
                                                String entrada = texto.substring(idx + 8).trim(); // lo que está
                                                                                                  // después de
                                                                                                  // ">
                                                                                                  // Input:"
                                                try {
                                                        int valor = Integer.parseInt(entrada);
                                                        if (valor >= 0 && valor <= 255) {
                                                                // Pasar al controlador
                                                                controlador_principal.leer_Teclado(valor);
                                                                // Opcional: mostrar confirmación en la terminal
                                                                terminal_Text_Area.append("\nValor capturado: "
                                                                                + valor + "\n");

                                                                bloqueo = false;

                                                                // Actualizar las tablas.
                                                                actualizar_Tablas();

                                                        } else {
                                                                terminal_Text_Area.append(
                                                                                "\nError: valor fuera de rango (0-255)\n");
                                                        }
                                                } catch (NumberFormatException e) {
                                                        terminal_Text_Area.append(
                                                                        "\nError: entrada invalida, debe ser numerica\n");
                                                }
                                        }
                                }
                        }
                });
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new Ventana_Principal().setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Almacenamiento_Label;
    private javax.swing.JLabel BCP_Label;
    private javax.swing.JButton Cargar_Archivos_BTN;
    private javax.swing.JButton Ejecutar_BTN;
    private javax.swing.JButton Estadisticas_BTN;
    private javax.swing.JButton Limpiar_BTN;
    private javax.swing.JLabel Lista_Procesos_Label;
    private javax.swing.JLabel Memoria_Label;
    private javax.swing.JButton Paso_A_Paso_BTN;
    private javax.swing.JTable Tabla_Almacenamiento;
    private javax.swing.JTable Tabla_BCP;
    private javax.swing.JTable Tabla_Estadisticas;
    private javax.swing.JTable Tabla_Memoria;
    private javax.swing.JTable Tabla_Procesos;
    private javax.swing.JLabel Terminal_Text_Area_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea terminal_Text_Area;
    // End of variables declaration//GEN-END:variables
}
